/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * Copyright 2018-2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __RTE_DEVICE_H
#define __RTE_DEVICE_H

/***********************************************************************************************************************
 * Driver name mapping
 **********************************************************************************************************************/
/* Enable peripheral */
#define RTE_USART0 1
/* Enable USART DMA */
#define RTE_USART0_DMA_EN 1

/***********************************************************************************************************************
 * Driver configuration
 **********************************************************************************************************************/
/* All USART Rx buffers lenght */
#define USART_RX_BUFFER_LEN 64
/* Enable RX buffer */
#define USART0_RX_BUFFER_ENABLE 1
/* Selected DMA channel number. */
#define RTE_USART0_DMA_RX_CH 4
/* Used DMA device. */
#define RTE_USART0_DMA_RX_DMA_BASE DMA0
/* Selected DMA channel number. */
#define RTE_USART0_DMA_TX_CH 5
/* Used DMA device. */
#define RTE_USART0_DMA_TX_DMA_BASE DMA0


#endif /* __RTE_DEVICE_H */
